<h1>Why we need NumPy?</h1>
NumPy is necessary because in Python we can not do certain operations on lists.  NumPy supports broadcasting, allowing you to perform element-wise operations on arrays of different shapes without the need for explicit loops. So when we convert a regular list into NumPy arrays and we can multiply something to all the values in a list with a single line of code.

Regular list in Python:

In [2]:
sample = [2,3,4,5]
print(sample*5)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


Using NumPy:

In [6]:
import numpy as np

sample = np.array([2,3,4,5])
print(sample*5)

[10 15 20 25]


<ul>
    <li>Arrays are also faster than lists. NumPy arrays are implemented in C and optimized for performance. They provide faster execution for numerical operations compared to Python lists.</li>
    <li>NumPy arrays use less memory than Python lists for storing numerical data. This is because they store elements of the same data type in contiguous memory locations, reducing overhead.</li>
    <li>NumPy offers a wide range of mathematical functions and operations (e.g., linear algebra, statistical functions, Fourier transforms) that are optimized for performance.</li>
    <li>Many NumPy operations are vectorized, meaning they can be applied to entire arrays without the need for explicit loops, making code more concise and often faster. <a href="https://www.intel.com/content/www/us/en/developer/articles/technical/vectorization-a-key-tool-to-improve-performance-on-modern-cpus.html">Learn more here.</a></li>
    <li>All elements in a NumPy array are of the same type, which can prevent bugs related to mixed data types and improve performance.</li>
    <li>NumPy provides explicit type casting, allowing for better control over the precision and memory usage of nulerical computations.</li>
</ul>

</ul>

</ul>
tations.

<h1>Let’s begin with NumPy</h1>

In [7]:
import numpy as np

To initialize a NumPy array,

In [8]:
list_array = np.array([1, 2, 3, 4, 5])
tuple_array = np.array((1, 2, 3, 4, 5))

A 2D array will look like this,

In [9]:
arr = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.float32)

Here dtype is used for type casting, so despite the given elements being integers, the array will convert everything to floats.

Even when you don’t manually set the data type:

When the elements of a NumPy array are mixed types, then the array's type will be upcast to the highest level type. This means that if an array input has mixed int and float elements, all the integers will be cast to their floating-point equivalents. If an array is mixed with int, float, and string elements, everything is cast to strings.

<h1>A couple of operations to get started.</h1>
<h2>1. Copying:</h2>

In [10]:
a = np.array([1,2,3])
b = a
b[0] = 5

print(a)
print(b)

[5 2 3]
[5 2 3]


So this is a big issue. We set b equals to a and if we change any value of b, a changes as well. This is not supposed to happen but Python actually sets a and b to the same memory location. So solve this issue NumPy has a copy function,

In [11]:
a = np.array([1,2,3])
b = a.copy()

b[0]= 5

print(a)
print(b)

[1 2 3]
[5 2 3]


<h2>2. Casting:</h2>

We cast NumPy arrays through their inherent astype function.

In [12]:
arr = np.array([1,2,3])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int32
float32


Notice that we are using dtype to get the data type. It’s because,

In [13]:
type(arr)

numpy.ndarray

So to get the data type of the date inside a NumPy array, we need to use variable_name.dtype.

<h1>Null and Infinity</h1>

<h2>1. NaN</h2>

We might need some values to be blank but we have to put something here to hold the space in the memory or have some existence inside the array. 

In [15]:
arr = np.array([np.nan, 1, 2])
print(arr)

[nan  1.  2.]


<h2>2. Infinity</h2>

To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

In [16]:
arr = np.array([np.inf, 5])

arr = np.array([-np.inf, 1])

In [18]:
np.array([np.inf, 3], dtype=np.int32) #this cannot be done, np.inf cannot take on an int type.

OverflowError: cannot convert float infinity to integer

In [19]:
np.array([np.inf, 3], dtype=np.float32) #this is right

array([inf,  3.], dtype=float32)

<h1>Populating the arrays and tinkering with dimensions</h1>

<h2>1. Ranged data</h2>

If we wanted to populate our array using a range of values we can use np.arange( ).

This following code will return an array with all the integers in the range [0, n); [ means inclusive, ) means exclusive:

In [22]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [23]:
arr = np.arange(-1, 4)
print(arr)

[-1  0  1  2  3]


For three arguments, m, n, and s, np.arange will return an array with the integers in the range [m, n) using a step size of s.

In [24]:
arr = np.arange(-1.5, 4, 2)
print(arr)

[-1.5  0.5  2.5]


This following one is a little weird as some might think this will give as an output of [0.1 1.1 2.1 3.1 4.1]. 

In [25]:
arr = np.arange(5.1)
print(arr)

[0. 1. 2. 3. 4. 5.]


To get that output we actually have to do this:

In [26]:
arr = np.arange(5) + 0.1
print(arr)

[0.1 1.1 2.1 3.1 4.1]


<u>np.linspace:</u>

To specify the number of elements in the returned array, rather than the step size, we can use the np.linspace function.

This function takes in a required first two arguments, for the start and end of the range, respectively. The end of the range is inclusive for np.linspace, unless the keyword argument endpoint is set to False. To specify the number of elements, we set the num keyword argument (its default value is 50).

In [27]:
arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

array([5. , 6.5, 8. , 9.5])


<h2>2. Reshaping Data</h2>

The function we use to reshape data in NumPy is np.reshape. It takes in an array and a new shape as required arguments. The new shape must exactly contain all the elements from the input array. For example, we could reshape an array with 12 elements to (4, 3), but we can't reshape it to (4, 4).

We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.

In [28]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print("The new array is {} \n and the shape of the array is {}".format(reshaped_arr, reshaped_arr.shape))

The new array is [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 
 and the shape of the array is (2, 2, 2)


<u>flatten():</u>

In [29]:
flattened = arr.flatten()
print(flattened)

[0 1 2 3 4 5 6 7]
